# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    # встановлює текст на віджети
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(70, 260, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btn_generate.setFont(font)
        self.btn_generate.setStyleSheet("color: #002f36;\n"
"font: 87 21pt \"Segoe UI Black\";\n"
"border: 3px dotted #002f36;\n"
"background-color: #c7f8ff;\n"
"border-radius: 10px;")
        self.btn_generate.setObjectName("btn_generate")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(40, 40, 289, 39))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.title.setFont(font)
        self.title.setStyleSheet("color: #002f36;\n"
"font: 87 21pt \"Segoe UI Black\";")
        self.title.setObjectName("title")
        self.cb_numbers = QtWidgets.QRadioButton(self.centralwidget)
        self.cb_numbers.setGeometry(QtCore.QRect(10, 160, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cb_numbers.setFont(font)
        self.cb_numbers.setStyleSheet("color: #001214;")
        self.cb_numbers.setObjectName("cb_numbers")
        self.cb_alphabet = QtWidgets.QRadioButton(self.centralwidget)
        self.cb_alphabet.setGeometry(QtCore.QRect(10, 200, 243, 28))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cb_alphabet.setFont(font)
        self.cb_alphabet.setStyleSheet("color: #001214;")
        self.cb_alphabet.setObjectName("cb_alphabet")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 110, 181, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(True)
        self.result.setFont(font)
        self.result.setStyleSheet("color: #001214;")
        self.result.setObjectName("result")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
# встановлює текст на віджети
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_generate.setText(_translate("MainWindow", "Згенерувати"))
        self.title.setText(_translate("MainWindow", "Генератор Паролів"))
        self.cb_numbers.setText(_translate("MainWindow", "Використовувати числа"))
        self.cb_alphabet.setText(_translate("MainWindow", "Використовувати літери"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
